(cl:defpackage message_tests-srv
  (:use )
  (:export
   "CHANGERATE"
   "<CHANGERATE-REQUEST>"
   "CHANGERATE-REQUEST"
   "<CHANGERATE-RESPONSE>"
   "CHANGERATE-RESPONSE"
   "CHANGESPEED"
   "<CHANGESPEED-REQUEST>"
   "CHANGESPEED-REQUEST"
   "<CHANGESPEED-RESPONSE>"
   "CHANGESPEED-RESPONSE"
   "TOGGLEFORWARD"
   "<TOGGLEFORWARD-REQUEST>"
   "TOGGLEFORWARD-REQUEST"
   "<TOGGLEFORWARD-RESPONSE>"
   "TOGGLEFORWARD-RESPONSE"
  ))

